added some specs
Valve/mxmnd pull request #2
Opened 2018-10-14 11:37 UTC by timur-rimsky

2018-10-20 15:10 UTC, Valve requested changes
Please fix the formatting first. 
Also the spec actually failed. So you added a spec that failed, see Travis output. Looks like you didn't commit the changes in the Gemfile (or gemspec).

2018-10-20 15:10 UTC, Valve commented on spec/mxmnd_spec.rb
> +describe 'Mxmnd.city response' do
Ruby uses 2 spaces for indentation, you seem to be using more. 
Please install Rubocop locally and run your code through it to see some of the styling issues

2018-10-20 15:10 UTC, Valve commented on spec/mxmnd_spec.rb
> +# i've changed "Content-Length" property of recorded response from 1476 to 2515
whoa this is weird, why aren't you indenting comments at the same level?

2018-10-20 15:10 UTC, Valve commented on spec/tmp/mxmnd_res.txt
> +HTTP/1.1 200 OK
this file should be in spec/fixtures

2018-11-05 08:39 UTC, closed without merging

2018-11-05 13:22 UTC, Valve commented
@timur-rimsky why did you close the PR?

2018-11-05 14:02 UTC, timur-rimsky commented
потому что не получалось сделать новый пул реквест

On Mon, Nov 5, 2018 at 4:22 PM Valentin Vasilyev <notifications@github.com>
wrote:

> @timur-rimsky <https://github.com/timur-rimsky> why did you close the PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Valve/mxmnd/pull/2#issuecomment-435871518>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ApIWFtDkz8ZIFfe0f69YI4AS_IP94DbNks5usDuOgaJpZM4XbFhC>
> .
>