corrected errors
Valve/mxmnd pull request #3
Opened 2018-11-05 08:42 UTC by timur-rimsky

I've corrected errors
made some changes in gem file
so specs pass

2018-11-09 16:44 UTC, Valve commented
@timur-rimsky mention me like that @Valve so that I get notifications.

2018-11-09 17:17 UTC, Valve requested changes
Overall it's much better this time.
I left some comments regarding the stylistics of your code.

You can also be more specific about your spec expectation, instead of saying that name should have 8 locales, you can just directly verify that a name is %w[a b c].
But overall it's a good progress.

2018-11-09 17:17 UTC, Valve commented on spec/mxmnd_spec.rb
> +  	url = 'https://geoip.maxmind.com/geoip/v2.1/city/45.17.22.11'
indentation is off here

2018-11-09 17:17 UTC, Valve commented on spec/mxmnd_spec.rb
> +    path = './spec/features/mxmnd_res.txt'
better be more specific and call it `response_path`

2018-11-09 17:17 UTC, Valve commented on spec/mxmnd_spec.rb
> +    ruby_headers = {
these headers are not ruby-specific, so better just call them `headers` or `request headers`

2018-11-09 17:17 UTC, Valve commented on spec/mxmnd_spec.rb
> +    @response = JSON.parse(Net::HTTP.get(url, '/'))
the use of instance variables in specs is discouraged, Please use `let` for this.
e.g.
```
let(:response) { JSON.parse... }
```

Then you can just use `response` variable inside your spec examples.

2018-11-09 17:17 UTC, Valve commented on spec/mxmnd_spec.rb
> +    keys_array = [
keys (anything plural is array be definition)

2018-11-09 17:17 UTC, Valve commented on spec/mxmnd_spec.rb
> +      expect(@response['subdivisions'].is_a?(Array)).to be(true)
there should be a matcher that does that in one check, eg:

```
expect(obj).to be_a(type)
```

2018-11-09 17:17 UTC, Valve commented on spec/spec_helper.rb
> +def hash_including_locales(dict, num_of_locales)
this method doesn't care if second argument is locales or something else, a better way is to just bring this into the spec example, e.g. `expect(dict['name'].size).to eq 8`.
Any custom matching methods make spec reading more confusing.

2018-11-17 09:05 UTC, timur-rimsky commented
@Valve, I've made corrections according to your notices. 
Please look it for mistakes.

2018-11-17 15:54 UTC, merged